### PR TITLE
Fixing CI/CD workflow

### PR DESCRIPTION
**Pull request by jonico**
* use newer gcp setup action that uses new way of setting env variables

### CODE REVIEW

**Review by imjohnbo — APPROVED** [review]
🚀

**Comment by imjohnbo** [comment]
@bharathkkb we update this instead to `google-github-actions/setup-gcloud`, probably `@v1`? @jonico mind testing with that version?

**Comment by jonico** [comment]
@imjohnbo: updated to the new namespace in latest commit, but I could not find a v1 tag over there, sticking with https://github.com/google-github-actions/setup-gcloud/tree/v0.2.1

The CI runs will fail until this PR gets merged as a forked PR does not get access to the GITHUB_TOKEN for the package registry.

**Comment by imjohnbo** [comment]
> @imjohnbo: updated to the new namespace in latest commit, but I could not find a v1 tag over there, sticking with https://github.com/google-github-actions/setup-gcloud/tree/v0.2.1

You're right – I could swear I had just seen a `v1` 🤔 👍 

> The CI runs will fail until this PR gets merged as a forked PR does not get access to the GITHUB_TOKEN for the package registry.

Yeah, I think we need to update some Google secrets too.... wondering if you could point me to a working run elsewhere to verify.

**Comment by imjohnbo** [comment]
Ultimately I need to fix the CI 😀

**Comment by bharathkkb** [comment]
@imjohnbo we havent cut a v1 yet. Waiting to clean up the old actions within current `google-github-actions/setup-gcloud` before we cut a v1.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
